import * as fs from 'fs';
import * as path from 'path';

const BACKEND_SRC_DIR = path.resolve(__dirname, '..');
const PROJECT_ROOT = path.resolve(BACKEND_SRC_DIR, '../../..');
const OUTPUT_FILE = path.resolve(PROJECT_ROOT, 'docs/CODEBASE_MAP.md');

interface SymbolInfo {
  name: string;
  type: string;
  line: number;
}

interface FileMap {
  relativePath: string;
  symbols: SymbolInfo[];
}

function scanDirectory(dir: string, fileList: string[] = []): string[] {
  const files = fs.readdirSync(dir);
  for (const file of files) {
    const filePath = path.join(dir, file);
    const stat = fs.statSync(filePath);
    if (stat.isDirectory()) {
      if (file !== 'node_modules' && file !== 'dist' && file !== 'build') {
        scanDirectory(filePath, fileList);
      }
    } else if (filePath.endsWith('.ts') && !filePath.endsWith('.test.ts') && !filePath.endsWith('.d.ts')) {
      fileList.push(filePath);
    }
  }
  return fileList;
}

function extractSymbols(filePath: string): SymbolInfo[] {
  const content = fs.readFileSync(filePath, 'utf-8');
  const lines = content.split('\n');
  const symbols: SymbolInfo[] = [];

  // Patterns to match exports
  const patterns = [
    { type: 'Class', regex: /^\s*export\s+class\s+(\w+)/ },
    { type: 'Function', regex: /^\s*export\s+(?:async\s+)?function\s+(\w+)/ },
    { type: 'Constant/Arrow', regex: /^\s*export\s+const\s+(\w+)\s*(?::\s*[^=]+)?\s*=\s*(?:\([^)]*\)|[a-zA-Z0-9_]+)\s*=>/ },
    { type: 'Constant/Object', regex: /^\s*export\s+const\s+(\w+)\s*(?::\s*[^=]+)?\s*=\s*\{/ },
    { type: 'Interface', regex: /^\s*export\s+interface\s+(\w+)/ },
    { type: 'Type', regex: /^\s*export\s+type\s+(\w+)/ },
    { type: 'Enum', regex: /^\s*export\s+enum\s+(\w+)/ },
  ];

  lines.forEach((line, index) => {
    // Avoid checking comments
    if (line.trim().startsWith('//') || line.trim().startsWith('*') || line.trim().startsWith('/*')) {
      return;
    }
    
    // Handle standard patterns
    for (const pattern of patterns) {
      const match = line.match(pattern.regex);
      if (match && match[1]) {
        if (!symbols.some(s => s.name === match[1] && s.line === index + 1)) {
          symbols.push({
            name: match[1],
            type: pattern.type,
            line: index + 1
          });
        }
        break;
      }
    }

    // Handle multi-re-exports like export { a as b, c }
    const reExportMatch = line.match(/^\s*export\s+\{([^}]+)\}/);
    if (reExportMatch && reExportMatch[1]) {
      const parts = reExportMatch[1].split(',');
      parts.forEach(part => {
        const trimmed = part.trim();
        if (!trimmed) return;
        
        // Match "symbol as alias" or just "symbol"
        const aliasMatch = trimmed.match(/(\w+)\s+as\s+(\w+)/);
        const symName = aliasMatch ? aliasMatch[2] : trimmed.match(/(\w+)/)?.[1];
        
        if (symName && !symbols.some(s => s.name === symName && s.line === index + 1)) {
          symbols.push({
            name: symName,
            type: 'Export/Alias',
            line: index + 1
          });
        }
      });
    }
  });

  return symbols;
}

function main() {
  console.log(`Scanning backend source directory: ${BACKEND_SRC_DIR}...`);
  const files = scanDirectory(BACKEND_SRC_DIR);
  const maps: FileMap[] = [];

  for (const file of files) {
    const symbols = extractSymbols(file);
    if (symbols.length > 0) {
      const relativePath = path.relative(PROJECT_ROOT, file);
      maps.push({
        relativePath,
        symbols
      });
    }
  }

  // Sort files alphabetically
  maps.sort((a, b) => a.relativePath.localeCompare(b.relativePath));

  // Build markdown content
  let markdown = `# PriceStalker Backend Codebase Symbol Map\n\n`;
  markdown += `*This file is auto-generated by the codebase map script. It maps all exported functions, classes, interfaces, and types to facilitate AI agent semantic navigation and fast file location.*\n\n`;
  markdown += `Total Files Mapped: **${maps.length}**\n\n`;
  
  markdown += `## 🔍 Symbol Index\n\n`;
  markdown += `| Symbol | Type | File | Line |\n`;
  markdown += `| :--- | :--- | :--- | :--- |\n`;

  // Aggregate all symbols for the table index
  const allSymbols: { name: string; type: string; file: string; line: number }[] = [];
  for (const map of maps) {
    for (const sym of map.symbols) {
      allSymbols.push({
        name: sym.name,
        type: sym.type,
        file: map.relativePath,
        line: sym.line
      });
    }
  }

  // Sort symbols alphabetically
  allSymbols.sort((a, b) => a.name.localeCompare(b.name));

  for (const sym of allSymbols) {
    const fileLink = `[${path.basename(sym.file)}](file://${path.resolve(PROJECT_ROOT, sym.file)}#L${sym.line})`;
    markdown += `| \`${sym.name}\` | **${sym.type}** | ${fileLink} | \`L${sym.line}\` |\n`;
  }

  markdown += `\n## 📂 Detailed File Mapping\n\n`;
  for (const map of maps) {
    const fileFullPath = path.resolve(PROJECT_ROOT, map.relativePath);
    markdown += `### 📄 [${map.relativePath}](file://${fileFullPath})\n\n`;
    markdown += `| Exported Symbol | Type | Line | Link |\n`;
    markdown += `| :--- | :--- | :--- | :--- |\n`;
    for (const sym of map.symbols) {
      markdown += `| \`${sym.name}\` | **${sym.type}** | \`L${sym.line}\` | [View](file://${fileFullPath}#L${sym.line}) |\n`;
    }
    markdown += `\n`;
  }

  fs.writeFileSync(OUTPUT_FILE, markdown, 'utf-8');
  console.log(`Codebase map generated successfully at: ${OUTPUT_FILE}`);
}

main();
