export interface RetailerConfig {
  id: number;
  domain: string;
  name: string | null;
  status: string | null;
  status_history: { status: string; timestamp: string }[];
  use_proxy: boolean;
  use_browser: boolean;
  use_remote_scraper: boolean;
  is_js_heavy: boolean;
  currency_hint: string | null;
  name_selectors: string[];
  retailer_name_selectors: string[];
  price_selectors: string[];
  deal_price_selectors: string[];
  original_price_selectors: string[];
  member_price_selectors: string[];
  image_selectors: string[];
  stock_selectors: string[];
  in_stock_phrases: string[];
  out_of_stock_phrases: string[];
  pre_order_phrases: string[];
  member_only_phrases: string[];
  pre_order_price_selectors: string[];
  exclusion_selectors: string[];
  jsonld_image_key: string | null;
  jsonld_price_key: string | null;
  jsonld_name_key: string | null;
  user_agent: string | null;
  referrer: string | null;
  custom_selectors: any;
  description: string | null;
  skip_denoising?: boolean;
  ai_selectors?: { price?: string[]; image?: string[] } | null;
  active: boolean;
  selector_metadata?: any;
  created_at: Date;
  updated_at: Date;
}
