INSERT INTO system_settings (key, value) VALUES
  ('ai_max_retries', '2'),
  ('ai_timeout', '30000'),
  ('debug_page_enabled', 'true'),
  ('deepseek_model', 'deepseek-chat'),
  ('default_referrer', 'https://www.google.com/'),
  ('generic_ai_image_selectors', E'["link[rel=\\"preload\\"][as=\\"image\\"]","img#landingImage","img#main-image","img.main-image","img.hero-image","img[class*=\\"product-image\\" i]","img[class*=\\"product__image\\" i]","img[class*=\\"gallery\\" i]","img[data-testid*=\\"image\\" i]"]'),
  ('generic_ai_price_selectors', E'["[class*=\\"price\\" i]","[class*=\\"Price\\" i]","[data-testid*=\\"price\\" i]","[data-automation*=\\"price\\" i]","[data-automation*=\\"Price\\" i]","[itemprop=\\"price\\"]","[data-price]","[data-price-amount]","[data-product-price]"]'),
  ('generic_exclusion_selectors', '[]'),
  ('generic_in_stock_phrases', '["in stock", "instock", "add to cart", "add to basket", "buy now", "available now", "add to trolley", "clearance", "on sale", "special offer", "limited stock", "available", "ready to ship"]'),
  ('generic_out_of_stock_phrases', '["out of stock", "sold out", "currently unavailable", "not available", "backorder", "back-order", "notify me when available", "coming soon"]'),
  ('generic_pre_order_phrases', '["pre-order", "preorder", "available starting", "expected to ship", "release date", "pre-ordering"]'),
  ('generic_pre_order_price_selectors', '[]'),
  ('generic_stock_selectors', E'["[itemprop=\\"availability\\"]",".stock-status",".availability","[class*=\\"stock-status\\" i]","[class*=\\"availability\\" i]"]'),
  ('groq_model', 'llama-3.3-70b-versatile'),
  ('jsonld_image_key', 'image'),
  ('jsonld_name_key', 'name'),
  ('jsonld_price_key', 'price'),
  ('mistral_model', 'mistral-large-latest'),
  ('prefer_jsonld_image', 'true'),
  ('registration_enabled', 'true'),
  ('retailer_updates_disabled', 'false'),
  ('scheduler_disabled', 'false'),
  ('searxng_enabled', 'false'),
  ('searxng_url', '')
ON CONFLICT (key) DO NOTHING;
